version: "3"

services:
    db:
        image: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=emenu

    cronjobs:
        build: .
        command: ["cron", "-f"]

    web:
        build: .
        depends_on:
            - db
            - cronjobs
        ports:
            - "8000:8000"
        command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/code
